ARG ROCM_VERSION=7.2
ARG ROCM_IMAGE_NAME=rocm/dev-ubuntu-22.04
ARG ROCM_IMAGE_TAG=${ROCM_VERSION}-complete

FROM "${ROCM_IMAGE_NAME}:${ROCM_IMAGE_TAG}"

ARG ROCM_SYSTEMS_REPO=https://github.com/ROCm/rocm-systems.git
ARG ROCM_SYSTEMS_BRANCH=develop
ARG GPU_TARGETS=gfx950

ENV ROCM_PATH=/opt/rocm
ENV WORKDIR=/workspace
ENV MPI_INSTALL_PREFIX=/opt/ompi
ENV ROCM_SYSTEMS_DIR=${WORKDIR}/rocm-systems
ENV RCCL_HOME=${ROCM_SYSTEMS_DIR}/projects/rccl
ENV RCCL_TESTS_HOME=${ROCM_SYSTEMS_DIR}/projects/rccl-tests
ENV RCCL_INSTALL_DIR=${RCCL_HOME}/build

RUN mkdir -p ${WORKDIR}
WORKDIR ${WORKDIR}

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    git \
    make \
    cmake \
    build-essential \
    libnuma-dev \
    pkg-config \
    wget \
    jq \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.6.tar.gz \
    && mkdir -p ompi4 \
    && tar -zxf openmpi-4.1.6.tar.gz -C ompi4 --strip-components=1 \
    && cd ompi4 \
    && mkdir build \
    && cd build \
    && ../configure --prefix=${MPI_INSTALL_PREFIX} --disable-oshmem --disable-mpi-fortran --enable-orterun-prefix-by-default \
    && make -j$(nproc) install \
    && cd ${WORKDIR} \
    && rm -rf ompi4 openmpi-4.1.6.tar.gz

RUN git clone --no-checkout --filter=blob:none "${ROCM_SYSTEMS_REPO}" "${ROCM_SYSTEMS_DIR}" \
    && cd "${ROCM_SYSTEMS_DIR}" \
    && git sparse-checkout init --cone \
    && git sparse-checkout set projects/rccl projects/rccl-tests \
    && git checkout "${ROCM_SYSTEMS_BRANCH}" \
    && git submodule update --init --depth=1 \
        projects/rccl/ext-src/json \
        projects/rccl/ext-src/mscclpp \
        projects/rccl/ext-src/rocSHMEM

RUN cd ${RCCL_HOME} \
    && ./install.sh \
        --amdgpu_targets=${GPU_TARGETS} \
        --prefix=${RCCL_INSTALL_DIR} \
        --disable-msccl-kernel \
        -j$(nproc)

RUN cd ${RCCL_TESTS_HOME} \
    && mkdir -p build \
    && cd build \
    && export NCCL_HOME="${RCCL_INSTALL_DIR}" \
    && cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DUSE_MPI=ON \
        -DNCCL_ROOT="${RCCL_INSTALL_DIR}" \
        -DCMAKE_PREFIX_PATH="${RCCL_INSTALL_DIR};${MPI_INSTALL_PREFIX};${ROCM_PATH}" \
        -DCMAKE_LIBRARY_PATH="${RCCL_INSTALL_DIR}/lib" \
        -DCMAKE_INCLUDE_PATH="${RCCL_INSTALL_DIR}/include" \
        -DGPU_TARGETS=${GPU_TARGETS} \
        -DROCM_PATH=${ROCM_PATH} \
        .. \
    && make -j$(nproc)

WORKDIR ${WORKDIR}
